### PR TITLE
fix: home/canvases logo as Link, small clean up

### LINKED ISSUE #4280: Canvas: logo/home as real link
### Context
On the Canvas page, home/logo navigation is not a real link.

### Observed behavior
Cannot use standard browser patterns:
- Cmd/Ctrl+Click open in new tab
- middle click
- right-click context menu open in new tab

Navigation is handled via JS click handler instead of anchor semantics.

### Suggested improvement
Use a real `<a href>` or framework `Link` component for logo/home navigation so expected browser behaviors work out of the box.

### PR DESCRIPTION
**Pull request by andrecalil**
Replaced the `button` for a router `Link` on the main logo. Also removed several `onLogoClick` that weren't doing anything relevant.

Fixes #4280.

### CODE REVIEW

File: web_src/src/components/OrganizationMenuButton.tsx [hunk 1]
```diff
@@ -1,3 +1,4 @@
+/* eslint-disable max-lines-per-function */
```
Comment (lucaspin) [inline web_src/src/components/OrganizationMenuButton.tsx]: Why was this added?

Comment (andrecalil) [reply web_src/src/components/OrganizationMenuButton.tsx]: Oh. I should have removed it. 
VSCode was warning the whole file, making it almost unreadable, because of the function size. 

But you're right, I wasn't supposed to have committed it. I'll update.

Comment (andrecalil) [reply web_src/src/components/OrganizationMenuButton.tsx]: Update: I think a proper refactor of the component, to break it down a bit, would be the right move.
But I chose to submit a more concise changeset since it's my first time around here.

Comment (lucaspin) [reply web_src/src/components/OrganizationMenuButton.tsx]: Good intuition. Maybe we can refactor it in another pull request.

Comment (andrecalil) [reply web_src/src/components/OrganizationMenuButton.tsx]: Hey Lucas, removed the lint bypass for now

**Review by shiroyasha — APPROVED** [review]

**Review by lucaspin — APPROVED** [review]

**Comment by andrecalil** [comment]
Folks, gonna ask a dumb question because I'm not into the full flow: I don't get to merge this, right?

**Comment by shiroyasha** [comment]
@andrecalil looks good! The only thing missing before we can merge it is do the DCO check. 
https://github.com/superplanehq/superplane/blob/main/docs/contributing/commit_sign-off.md

Let me know if you need help setting this up. I'm happy to help.

**Comment by lucaspin** [comment]
@andrecalil code looks good, but before we merge, you'll have to sign-off your commits. Check https://github.com/superplanehq/superplane/blob/main/docs/contributing/commit_sign-off.md for how to do it. Then, we can merge it.

---

Edit: @shiroyasha beat me to the comment :)

**Comment by andrecalil** [comment]
Done. Should I rebase the PR?
`git fetch upstream && git rebase upstream/main` or directly via UI?

**Comment by lucaspin** [comment]
@andrecalil all good. Will merge once CI is green. Thanks for the pull request!
