### PR TITLE
fix: allow expressions in GitHub comment repository

### LINKED ISSUE #3226: GitHub comment rejects repo expression
**Description:**  
`github.createIssueComment` fails setup when `repository` is configured with an expression (for example, from `github.onWorkflowRun` payload), even though the resolved repository is accessible.

**Steps to reproduce:**  
1. In a canvas, add `github.onWorkflowRun` and `github.createIssueComment`.  
2. Set `github.createIssueComment.repository` to `{{$["github.onWorkflowRun failed test"].data.repository.full_name}}`.  
3. Save/apply configuration.

**Expected / Actual:**  
Expected: expression is accepted and validated against the resolved value at runtime.  
Actual: setup fails with `repository {{$["github.onWorkflowRun failed test"].data.repository.full_name}} is not accessible to app installation`.

**Implementation note:**  
`github.createIssueComment` validates `repository` during setup via `ensureRepoInMetadata`, which compares the raw configured string against installation repository names. Expression strings are therefore treated as literal values and fail validation. In contrast, `cursor.launchAgent` setup only performs basic non-empty field checks and does not validate repository access against installation metadata, so expression-based values are accepted there.

Image

### PR DESCRIPTION
**Pull request by hadzija7**
## Summary
- skip setup-time installation repository validation in `github.createIssueComment` when `repository` is an expression template
- keep existing validation behavior for literal repository values
- add a focused setup test covering expression-based `repository` configuration

## Why
- fixes #3226 where `github.createIssueComment` fails setup with `repository ... is not accessible to app installation` when configured with expression values

## Test plan
- [x] Added unit test: `repository expression skips setup validation`
- [ ] Run full test suite

### CODE REVIEW

File: pkg/integrations/github/create_issue_comment.go [hunk 1]
```diff
@@ -120,6 +121,12 @@ func (c *CreateIssueComment) Setup(ctx core.SetupContext) error {
 		return errors.New("body is required")
 	}
 
+	// Repository can be expression-based (resolved at runtime), so skip
+	// setup-time installation validation for templated values.
+	if strings.Contains(config.Repository, "{{") {
+		return nil
+	}
+
```
Comment (forestileao) [inline pkg/integrations/github/create_issue_comment.go]: The reported bug happens inside ensureRepoInMetadata. Let's remove it from here and add a expression regex validation in [ensureRepoInMetadata](https://github.com/hadzija7/superplane/blob/877453ab3b05df459af120d7fb9c9e60a2c9f67b/pkg/integrations/github/common.go#L46-L52).

an example of regex validation is in https://github.com/hadzija7/superplane/blob/877453ab3b05df459af120d7fb9c9e60a2c9f67b/pkg/configuration/validation.go#L262

If hasExpressions -> ignore the check.

Note: I noticed we are doing the same thing in bitbucket

Comment (hadzija7) [reply pkg/integrations/github/create_issue_comment.go]: hey @forestileao, can you check now?

File: pkg/integrations/github/common.go [hunk 2]
```diff
@@ -13,6 +14,8 @@ import (
 	"github.com/superplanehq/superplane/pkg/crypto"
 )
 
+var expressionPlaceholderRegex = regexp.MustCompile(`(?s)\{\{.*?\}\}`)
```
[the remark this answers is not in the document]
Comment (hadzija7) [reply pkg/integrations/github/common.go:17]: could maybe refactor this in a separate PR? @forestileao

**Comment by forestileao** [comment]
@hadzija7 PR merged, thank you :)
